### ISSUE TITLE
Sustainability/Integrity 

### ISSUE THREAD

**Issue by harshrajm** [SJSUFall2019-CMPE272/AgriFund#4]
1. To pull off a project at this scale will require a highly scalable and available system. This comes with a high cost, how much of the donations would go in maintaining the system? 
2. How would you make sure that the money given to a farmer is being used for farming?
3. Will the application feature integrations with genuine/certified online marketplaces for farmers? This could help in misuse of funds.

**Comment by dhanasreeA** [comment]
1. Any funds will solely go towards the cause they were donated for. the system doesn't incur massive costs, just regular maintanence costs, which will be covered by sponsors. Since it's a people project, Government fundings maybe a solution for maintaining the system.

2. As part of the Future developments, we plan on creating a service where bills for the expenditures are updated regularly.

3. As of now, there's no such plan since most of the supplies required for farming are seldom bought from online marketplaces.
